Repository moondance-labs/tanssi-docs, pull requests merged in 2024-04, with the labels that each got.

#133 Clean up node operator snippets and images
  .snippets/code/node-operators/appchain-node/rpc-docker/docker-command.md
  .snippets/code/node-operators/block-producers/onboarding/run-a-block-producer/block-producer-docker/docker-command.md
  .snippets/code/node-operators/block-producers/operational-tasks/manage-your-account/terminal/generate-session-keys.md
  .snippets/code/node-operators/block-producers/operational-tasks/upgrade-your-node/upgrade-docker/terminal/docker-stop.md
  .snippets/text/node-operators/appchain-node/fetching-bootnode-section.md
  .snippets/text/node-operators/appchain-node/intro.md
  .snippets/text/node-operators/appchain-node/run-flags.md
  .snippets/text/node-operators/block-producers/onboarding/run-a-block-producer/intro.md
  .snippets/text/node-operators/installing-docker.md
  .snippets/text/node-operators/optimized-binaries-note.md
  images/node-operators/block-producers/offboarding/account/account-1.webp
  images/node-operators/block-producers/offboarding/account/account-2.webp
  images/node-operators/block-producers/offboarding/account/account-3.webp
  images/node-operators/block-producers/offboarding/account/account-4.webp
  images/node-operators/block-producers/offboarding/account/account-5.webp
  images/node-operators/block-producers/offboarding/account/account-6.webp
  images/node-operators/block-producers/offboarding/account/account-7.webp
  images/node-operators/block-producers/offboarding/account/account-8.webp
  images/node-operators/block-producers/onboarding/proxy-accounts/proxy-1.webp
  images/node-operators/block-producers/onboarding/proxy-accounts/proxy-2.webp
  images/node-operators/block-producers/onboarding/proxy-accounts/proxy-3.webp
  images/node-operators/block-producers/onboarding/proxy-accounts/proxy-4.webp
  images/node-operators/block-producers/onboarding/proxy-accounts/proxy-5.webp
  images/node-operators/block-producers/onboarding/proxy-accounts/proxy-6.webp
  images/node-operators/block-producers/onboarding/proxy-accounts/proxy-7.webp
  images/node-operators/block-producers/onboarding/proxy-accounts/proxy-8.webp
  images/node-operators/block-producers/operational-tasks/proxy/proxy-block-10.webp
  images/node-operators/block-producers/operational-tasks/proxy/proxy-block-11.webp
  images/node-operators/block-producers/operational-tasks/proxy/proxy-block-13.webp
  images/node-operators/block-producers/operational-tasks/proxy/proxy-block-14.webp
  images/node-operators/block-producers/operational-tasks/proxy/proxy-block-6.webp
  images/node-operators/block-producers/operational-tasks/proxy/proxy-block-9.webp
  node-operators/appchain-node/rpc-docker.md
  node-operators/block-producers/offboarding/account.md
  node-operators/block-producers/onboarding/proxy-accounts.md
  node-operators/block-producers/onboarding/run-a-block-producer/block-producer-docker.md
  node-operators/block-producers/operational-tasks/upgrade-your-node/upgrade-docker.md
  node-operators/block-producers/operational-tasks/upgrade-your-node/upgrade-systemd.md
Labels: A2 - Maintenance Minor

#134 Apply general fixes
  builders/tanssi-network/endpoints.md
  dapp-developers/developer-toolkit/substrate-api/chopsticks.md
  learn/framework/architecture.md
  node-operators/block-producers/offboarding/account.md
  node-operators/block-producers/onboarding/proxy-accounts.md
Labels: A2 - Maintenance Minor

#135 Relocate Proxy from Onboarding to Operational Tasks
  images/index-pages/node-operators/block-producers/operational-tasks/proxy-accounts-dark.webp
  images/index-pages/node-operators/block-producers/operational-tasks/proxy-accounts.webp
  images/node-operators/block-producers/operational-tasks/proxy-accounts/proxy-1.webp
  images/node-operators/block-producers/operational-tasks/proxy-accounts/proxy-2.webp
  images/node-operators/block-producers/operational-tasks/proxy-accounts/proxy-3.webp
  images/node-operators/block-producers/operational-tasks/proxy-accounts/proxy-4.webp
  images/node-operators/block-producers/operational-tasks/proxy-accounts/proxy-5.webp
  images/node-operators/block-producers/operational-tasks/proxy-accounts/proxy-6.webp
  images/node-operators/block-producers/operational-tasks/proxy-accounts/proxy-7.webp
  images/node-operators/block-producers/operational-tasks/proxy-accounts/proxy-8.webp
  node-operators/block-producers/onboarding/.pages
  node-operators/block-producers/onboarding/account-setup.md
  node-operators/block-producers/operational-tasks/.pages
  node-operators/block-producers/operational-tasks/proxy-accounts.md
Labels: A3 - Quick Fixes

#136 fix image path on proxy docs
  node-operators/block-producers/operational-tasks/proxy-accounts.md
Labels: A3 - Quick Fixes

#128 polkadotjs article scripts fixes
  .snippets/code/dapp-developers/developer-toolkit/substrate-api/polkadot-js-api/adding-accounts-mnemonic-ecdsa.ts
  .snippets/code/dapp-developers/developer-toolkit/substrate-api/polkadot-js-api/adding-accounts-mnemonic-sr25519.ts
  .snippets/code/dapp-developers/developer-toolkit/substrate-api/polkadot-js-api/adding-accounts-private-key-ecdsa.ts
  .snippets/code/dapp-developers/developer-toolkit/substrate-api/polkadot-js-api/balance-event.ts
  .snippets/code/dapp-developers/developer-toolkit/substrate-api/polkadot-js-api/basic-transactions.ts
  .snippets/code/dapp-developers/developer-toolkit/substrate-api/polkadot-js-api/batch-transactions.ts
  .snippets/code/dapp-developers/developer-toolkit/substrate-api/polkadot-js-api/payment-info.ts
  .snippets/code/dapp-developers/developer-toolkit/substrate-api/polkadot-js-api/query-subscriptions.ts
  .snippets/code/dapp-developers/developer-toolkit/substrate-api/polkadot-js-api/rpc-queries.ts
  .snippets/code/dapp-developers/developer-toolkit/substrate-api/polkadot-js-api/state-queries.ts
  .snippets/text/_common/general-js-tutorial-check.md
  dapp-developers/developer-toolkit/substrate-api/polkadot-js-api.md
Labels: A3 - Quick Fixes

#139 Hardware requirements for block producers
  .snippets/text/node-operators/block-producers/onboarding/run-a-block-producer/hardware-requirements.md
  node-operators/block-producers/onboarding/run-a-block-producer/block-producer-docker.md
  node-operators/block-producers/onboarding/run-a-block-producer/block-producer-systemd.md
Labels: A2 - Maintenance Minor

#142 Replaces dancebox url
  .snippets/text/node-operators/appchain-node/fetching-bootnode-section.md
  builders/tanssi-network/endpoints.md
  builders/tanssi-network/networks/dancebox/overview.md
  dapp-developers/developer-toolkit/substrate-api/sidecar-api.md
  dapp-developers/developer-toolkit/substrate-api/wallets/subwallet.md
  dapp-developers/developer-toolkit/substrate-api/wallets/talisman.md
  node-operators/block-producers/offboarding/account.md
  node-operators/block-producers/onboarding/account-setup.md
  node-operators/block-producers/operational-tasks/proxy-accounts.md
  variables.yml
Labels: A2 - Maintenance Minor

#143 bump client to v0.6.1
  .snippets/code/node-operators/block-producers/operational-tasks/upgrade-your-node/upgrade-docker/terminal/docker-stop.md
  node-operators/block-producers/operational-tasks/upgrade-your-node/upgrade-docker.md
  variables.yml
Labels: A3 - Quick Fixes

#145 Documentation on Pooled Staking (Theoretical)
  images/index-pages/learn/tanssi/network-features-dark.webp
  images/index-pages/learn/tanssi/network-features.webp
  images/index-pages/learn/tanssi/network-features/staking-dark.webp
  images/index-pages/learn/tanssi/network-features/staking.webp
  images/index-pages/learn/tanssi/technical-features-dark.webp
  images/index-pages/learn/tanssi/technical-features.webp
  images/learn/tanssi/staking/staking-1.webp
  images/learn/tanssi/staking/staking-2.webp
  images/learn/tanssi/staking/staking-3.webp
  images/learn/tanssi/staking/staking-4.webp
  images/learn/tanssi/staking/staking-5.webp
  images/learn/tanssi/staking/staking-6.webp
  learn/tanssi/.pages
  learn/tanssi/network-features/.pages
  learn/tanssi/network-features/index.md
  learn/tanssi/network-features/staking.md
  learn/tanssi/technical-features.md
  node-operators/block-producers/offboarding/account.md
  node-operators/block-producers/onboarding/account-setup.md
  variables.yml
Labels: A0 - New Content
