Repository moondance-labs/tanssi-docs, pull requests merged in 2024-01, with the labels that each got.

#70 Starts Appchains in the Learn Section
  images/index-pages/learn/appchains-dark.png
  images/index-pages/learn/appchains.png
  images/index-pages/learn/appchains/overview-dark.png
  images/index-pages/learn/appchains/overview.png
  images/index-pages/learn/appchains/runtime-features-dark.png
  images/index-pages/learn/appchains/runtime-features.png
  images/learn/appchains/overview/dark-overview-1.png
  images/learn/appchains/overview/dark-overview-2.png
  images/learn/appchains/overview/light-overview-1.png
  images/learn/appchains/overview/light-overview-2.png
  images/learn/appchains/runtime-features/dark-runtime-features-1.png
  images/learn/appchains/runtime-features/light-runtime-features-1.png
  images/learn/tanssi/overview/dark-overview-1.png
  images/learn/tanssi/overview/dark-overview-2.png
  images/learn/tanssi/overview/light-overview-1.png
  images/learn/tanssi/overview/light-overview-2.png
  learn/.pages
  learn/appchains/.pages
  learn/appchains/index.md
  learn/appchains/overview.md
  learn/appchains/runtime-features.md
  learn/tanssi/overview.md
  learn/tanssi/technical-features.md
Labels: A0 - New Content

#66 Add YouTube Video Embeds to Docs Site
  builders/deploy/dapp.md
  builders/interact/ethereum-api/dev-env/hardhat.md
  builders/interact/ethereum-api/dev-env/remix.md
  builders/interact/ethereum-api/libraries/ethersjs.md
Labels: A2 - Maintenance Minor

#68 Add Viem Docs
  .snippets/code/ethereum-api/viem/balances.ts
  .snippets/code/ethereum-api/viem/browser-based-wallets.ts
  .snippets/code/ethereum-api/viem/compile.ts
  .snippets/code/ethereum-api/viem/deploy.ts
  .snippets/code/ethereum-api/viem/get.ts
  .snippets/code/ethereum-api/viem/increment.ts
  .snippets/code/ethereum-api/viem/read-chain-data.ts
  .snippets/code/ethereum-api/viem/reset.ts
  .snippets/code/ethereum-api/viem/transaction.ts
  .snippets/code/ethereum-api/viem/write-chain-data.ts
  .snippets/text/libraries/compile-ts.md
  .snippets/text/libraries/contract.md
  builders/interact/ethereum-api/libraries/.pages
  builders/interact/ethereum-api/libraries/viem.md
  images/builders/interact/ethereum-api/viem/viem-1.png
  images/builders/interact/ethereum-api/viem/viem-2.png
  images/builders/interact/ethereum-api/viem/viem-3.png
  images/builders/interact/ethereum-api/viem/viem-4.png
  images/builders/interact/ethereum-api/viem/viem-5.png
  images/builders/interact/ethereum-api/viem/viem-6.png
  images/index-pages/builders/interact/ethereum-api/libraries/viem-dark.png
  images/index-pages/builders/interact/ethereum-api/libraries/viem.png
Labels: A0 - New Content

#71 Update README.md
  README.md
Labels: A0 - New Content

#72 SEO-related fixes
  builders/build/templates/overview.md
  builders/interact/ethereum-api/dev-env/foundry.md
  builders/interact/ethereum-api/dev-env/hardhat.md
  builders/interact/ethereum-api/wallets/subwallet.md
  builders/interact/substrate-api/wallets/subwallet.md
  builders/tutorials/subsquid.md
  learn/tanssi/included-templates.md
  learn/tanssi/technical-features.md
Labels: A2 - Maintenance Minor

#76 Adds Escape Backlash for Target Blank
  builders/build/customize/adding-built-in-module.md
  builders/build/customize/adding-custom-made-module.md
  builders/build/customize/adding-external-module.md
  builders/build/customize/customizing-chain-specs.md
  builders/build/customize/prerequisites.md
  builders/build/templates/custom-runtime.md
  builders/build/templates/evm.md
  builders/build/templates/overview.md
  builders/build/templates/substrate.md
  builders/deploy/dapp.md
  builders/interact/ethereum-api/dev-env/foundry.md
  builders/interact/ethereum-api/dev-env/hardhat.md
  builders/interact/ethereum-api/indexers/subsquid.md
  builders/interact/ethereum-api/libraries/ethersjs.md
  builders/interact/ethereum-api/libraries/viem.md
  builders/interact/ethereum-api/libraries/web3py.md
  builders/interact/ethereum-api/wallets/metamask.md
  builders/interact/ethereum-api/wallets/subwallet.md
  builders/interact/ethereum-api/wallets/talisman.md
  builders/interact/substrate-api/indexers/subsquid.md
  builders/interact/substrate-api/polkadot-js-api.md
  builders/interact/substrate-api/sidecar-api.md
  builders/interact/substrate-api/wallets/subwallet.md
  builders/interact/substrate-api/wallets/talisman.md
  builders/tanssi-network/networks/dancebox/demo-evm-containerchain.md
  builders/tanssi-network/networks/dancebox/overview.md
  builders/tutorials/subsquid.md
  learn/framework/architecture.md
  learn/framework/modules.md
  learn/framework/overview.md
  learn/tanssi/included-templates.md
  learn/tanssi/overview.md
  learn/tanssi/technical-features.md
Labels: A2 - Maintenance Minor

#74 add termynal
  .snippets/code/builders/interact/ethereum-api/libraries/ethers/terminal/balances.md
  .snippets/code/builders/interact/ethereum-api/libraries/ethers/terminal/deploy.md
  .snippets/code/builders/interact/ethereum-api/libraries/ethers/terminal/get.md
  .snippets/code/builders/interact/ethereum-api/libraries/ethers/terminal/increment.md
  .snippets/code/builders/interact/ethereum-api/libraries/ethers/terminal/reset.md
  .snippets/code/builders/interact/ethereum-api/libraries/ethers/terminal/transaction.md
  builders/interact/ethereum-api/libraries/ethersjs.md
  js/termynal.min.js
Labels: A2 - Maintenance Minor

#73 Adding third party module - example
  .snippets/code/builders/build/customize/adding-external-module/terminal/patching.md
  builders/build/customize/adding-external-module.md
  images/builders/build/external-module/external-module-1.png
  images/builders/build/external-module/external-module-2.png
  variables.yml
Labels: A2 - Maintenance Minor

#77 New dApp Flow for SnapChains and Dedicated AppChains
  builders/deploy/dapp.md
  images/builders/deploy/dapp/dapp-1.png
  images/builders/deploy/dapp/dapp-10.png
  images/builders/deploy/dapp/dapp-11.png
  images/builders/deploy/dapp/dapp-12.png
  images/builders/deploy/dapp/dapp-13.png
  images/builders/deploy/dapp/dapp-14.png
  images/builders/deploy/dapp/dapp-2.png
  images/builders/deploy/dapp/dapp-3.png
  images/builders/deploy/dapp/dapp-4.png
  images/builders/deploy/dapp/dapp-5.png
  images/builders/deploy/dapp/dapp-6.png
  images/builders/deploy/dapp/dapp-7.png
  images/builders/deploy/dapp/dapp-8.png
  images/builders/deploy/dapp/dapp-9.png
Labels: A1 - Maintenance Major

#81 Fix Link on ReadMe
  README.md
Labels: A3 - Quick Fixes

#79 [Custom chain specs] Adding required parameters
  builders/deploy/dapp.md
Labels: A2 - Maintenance Minor

#83 Updates Transfer -> transferAllowDeath
  .snippets/code/builders/interact/substrate-api/polkadot-js-api/basic-transactions.js
  .snippets/code/builders/interact/substrate-api/polkadot-js-api/batch-transactions.js
  .snippets/code/builders/interact/substrate-api/polkadot-js-api/payment-info.js
  builders/interact/substrate-api/polkadot-js-api.md
Labels: A2 - Maintenance Minor

#78 Chopsticks - adapted article to Tanssi
  .snippets/code/builders/interact/substrate-api/chopsticks/chopsticks-1.md
  builders/interact/substrate-api/.pages
  builders/interact/substrate-api/chopsticks.md
  builders/interact/substrate-api/index.md
  images/builders/interact/substrate-api/chopsticks/chopsticks-1.png
  images/index-pages/builders/interact/substrate-api/chopsticks-dark.png
  images/index-pages/builders/interact/substrate-api/chopsticks.png
Labels: A0 - New Content

#86 Update Video Embed Link for ContainerChain Tutorial
  builders/deploy/dapp.md
Labels: A3 - Quick Fixes

#85 remove termynal js
  js/termynal.min.js
Labels: A3 - Quick Fixes

#88 Add Grammarly to PR Template
  .github/pull-request-template.md
Labels: A3 - Quick Fixes

#84 Added a few lines about tx_pause
  builders/build/templates/substrate.md
Labels: A2 - Maintenance Minor
