Repository moondance-labs/tanssi-docs, pull requests merged in 2024-08, with the labels that each got.

#177 updates generate node key command to call binary
  node-operators/block-producers/onboarding/run-a-block-producer/block-producer-systemd.md
Labels: A3 - Quick Fixes

#174 xcm precompile transfers
  .snippets/code/builders/toolkit/ethereum-api/precompiles/xcm-interface/XcmInterface.sol
  .snippets/text/builders/toolkit/ethereum-api/precompiles/security-note.md
  .snippets/text/builders/toolkit/ethereum-api/precompiles/xcm-interface/erc-20-note.md
  builders/toolkit/ethereum-api/precompiles/.pages
  builders/toolkit/ethereum-api/precompiles/batch.md
  builders/toolkit/ethereum-api/precompiles/call-permit.md
  builders/toolkit/ethereum-api/precompiles/cross-chain-transfers.md
  builders/toolkit/ethereum-api/precompiles/erc20.md
  images/builders/toolkit/ethereum-api/precompiles/xcm-interface/xcm-interface-1.webp
  images/builders/toolkit/ethereum-api/precompiles/xcm-interface/xcm-interface-2.webp
  images/builders/toolkit/ethereum-api/precompiles/xcm-interface/xcm-interface-3.webp
  images/builders/toolkit/ethereum-api/precompiles/xcm-interface/xcm-interface-4.webp
  images/builders/toolkit/ethereum-api/precompiles/xcm-interface/xcm-interface-5.webp
  images/builders/toolkit/ethereum-api/precompiles/xcm-interface/xcm-interface-6.webp
  images/index-pages/builders/toolkit/ethereum-api/precompiles/cross-chain-transfers-dark.webp
  images/index-pages/builders/toolkit/ethereum-api/precompiles/cross-chain-transfers.webp
  variables.yml
Labels: A0 - New Content

#176 add json rpc page
  builders/toolkit/ethereum-api/.pages
  builders/toolkit/ethereum-api/rpc.md
  images/index-pages/builders/toolkit/ethereum-api/rpc-dark.webp
  images/index-pages/builders/toolkit/ethereum-api/rpc.webp
Labels: A0 - New Content

#179 Updates client & sdk version
  variables.yml
Labels: A2 - Maintenance Minor
