Repository moondance-labs/tanssi-docs, pull requests merged in 2024-10, with the labels that each got.

#186 Proxies
  .snippets/code/builders/toolkit/ethereum-api/precompiles/proxy/proxy.sol
  builders/account-management/proxy-accounts.md
  builders/toolkit/ethereum-api/precompiles/.pages
  builders/toolkit/ethereum-api/precompiles/proxy.md
  images/builders/toolkit/ethereum-api/precompiles/proxy/proxy-1.webp
  images/builders/toolkit/ethereum-api/precompiles/proxy/proxy-2.webp
  images/builders/toolkit/ethereum-api/precompiles/proxy/proxy-3.webp
  images/builders/toolkit/ethereum-api/precompiles/proxy/proxy-4.webp
  images/builders/toolkit/ethereum-api/precompiles/proxy/proxy-5.webp
  images/index-pages/builders/toolkit/ethereum-api/precompiles/proxy-dark.webp
  images/index-pages/builders/toolkit/ethereum-api/precompiles/proxy.webp
  variables.yml
Labels: A0 - New Content, A2 - Maintenance Minor

#188 Fix links reported in October SEO Reports
  builders/build/templates/custom-runtime.md
  builders/build/templates/overview.md
  builders/manage/dapp/services-payment.md
  builders/toolkit/ethereum-api/libraries/ethersjs.md
  builders/toolkit/ethereum-api/libraries/viem.md
  builders/toolkit/ethereum-api/precompiles/external-assets-erc20.md
  builders/toolkit/ethereum-api/wallets/talisman.md
  builders/toolkit/substrate-api/wallets/talisman.md
  learn/framework/modules.md
  learn/tanssi/included-templates.md
  node-operators/block-producers/operational-tasks/proxy-accounts.md
Labels: A2 - Maintenance Minor

#189 Update pull-request-template.md
  .github/pull-request-template.md
Labels: A3 - Quick Fixes

#187 Integrate RainbowKit into a Tanssi demo apchain
  .snippets/code/builders/toolkit/wallet-integrations/rainbowkit/cli-quickstart.md
  .snippets/code/builders/toolkit/wallet-integrations/rainbowkit/layout.tsx
  .snippets/code/builders/toolkit/wallet-integrations/rainbowkit/pages.tsx
  .snippets/code/builders/toolkit/wallet-integrations/rainbowkit/providers.tsx
  .snippets/code/builders/toolkit/wallet-integrations/rainbowkit/providers1.tsx
  .snippets/code/builders/toolkit/wallet-integrations/rainbowkit/providers2.tsx
  .snippets/code/builders/toolkit/wallet-integrations/rainbowkit/wagmi.ts
  .snippets/code/builders/toolkit/wallet-integrations/rainbowkit/wagmi2.ts
  builders/toolkit/integrations/.pages
  builders/toolkit/integrations/wallet-integrations/.pages
  builders/toolkit/integrations/wallet-integrations/index.md
  builders/toolkit/integrations/wallet-integrations/rainbowkit.md
  images/builders/toolkit/integrations/wallet-integrations/rainbowkit/rainbowkit-1.webp
  images/builders/toolkit/integrations/wallet-integrations/rainbowkit/rainbowkit-2.webp
  images/builders/toolkit/integrations/wallet-integrations/rainbowkit/rainbowkit-3.webp
  images/index-pages/builders/toolkit/integrations/wallet-integrations-dark.webp
  images/index-pages/builders/toolkit/integrations/wallet-integrations.webp
  images/index-pages/builders/toolkit/integrations/wallet-integrations/rainbowkit-dark.webp
  images/index-pages/builders/toolkit/integrations/wallet-integrations/rainbowkit.webp
  variables.yml
Labels: A0 - New Content

#190 Changes constant to slow adjusting fee update
  learn/appchains/tx-fees.md
Labels: A2 - Maintenance Minor

#191 XCM delivery fees
  learn/framework/xcm.md
Labels: A2 - Maintenance Minor
