Repository moondance-labs/tanssi-docs, pull requests merged in 2024-06, with the labels that each got.

#159 Update Client to v0.6.3
  variables.yml
Labels: A3 - Quick Fixes

#160 Adds manage tokens guide
  builders/manage/dapp/.pages
  builders/manage/dapp/manage-tokens.md
  builders/manage/dapp/services-payment.md
  images/builders/manage/dapp/token-management/token-management-1.webp
  images/builders/manage/dapp/token-management/token-management-2.webp
  images/builders/manage/dapp/token-management/token-management-3.webp
  images/builders/manage/dapp/token-management/token-management-4.webp
  images/builders/manage/dapp/token-management/token-management-5.webp
  images/builders/manage/dapp/token-management/token-management-6.webp
  images/builders/manage/dapp/token-management/token-management-7.webp
  images/builders/manage/dapp/token-management/token-management-8.webp
  images/index-pages/builders/manage/dapp/manage-tokens-dark.webp
  images/index-pages/builders/manage/dapp/manage-tokens.webp
Labels: A0 - New Content

#155 Adds services payment article
  images/index-pages/learn/tanssi/included-templates-dark.webp
  images/index-pages/learn/tanssi/included-templates.webp
  images/index-pages/learn/tanssi/network-features-dark.webp
  images/index-pages/learn/tanssi/network-features.webp
  images/index-pages/learn/tanssi/technical-features-dark.webp
  images/index-pages/learn/tanssi/technical-features.webp
  learn/tanssi/technical-features.md
  variables.yml
Labels: A0 - New Content

#161 Adds xcm channels guide
  builders/manage/dapp/.pages
  builders/manage/dapp/xcm-channels.md
  images/builders/manage/dapp/xcm-channels/xcm-channels-1.webp
  images/builders/manage/dapp/xcm-channels/xcm-channels-2.webp
  images/builders/manage/dapp/xcm-channels/xcm-channels-3.webp
  images/builders/manage/dapp/xcm-channels/xcm-channels-4.webp
  images/builders/manage/dapp/xcm-channels/xcm-channels-5.webp
  images/index-pages/builders/manage/dapp/xcm-channels-dark.webp
  images/index-pages/builders/manage/dapp/xcm-channels.webp
Labels: A0 - New Content

#163 Adds open ports requirement
  .snippets/text/node-operators/block-producers/onboarding/run-a-block-producer/hardware-requirements.md
Labels: A2 - Maintenance Minor

#166 Updates binary template names
  builders/build/customize/adding-built-in-module.md
  builders/build/customize/adding-external-module.md
  builders/build/customize/customizing-chain-specs.md
  builders/build/customize/prerequisites.md
  node-operators/appchain-node/rpc-docker.md
  node-operators/appchain-node/rpc-systemd.md
Labels: A2 - Maintenance Minor

#162 Link Fixes
  README.md
  builders/manage/developer-portal/impersonate.md
  builders/manage/developer-portal/maintenance.md
  builders/manage/developer-portal/minting.md
  builders/manage/developer-portal/pause-transactions.md
  builders/manage/developer-portal/sudo.md
  builders/manage/developer-portal/upgrade.md
Labels: A2 - Maintenance Minor

#164 Text snippets for sudo and management accounts retrieval
  .snippets/text/builders/manage/dapp/locate-registration-account.md
  .snippets/text/builders/manage/dapp/prerequisites.md
  .snippets/text/builders/manage/locate-sudo-account.md
  builders/manage/dapp/manage-tokens.md
  builders/manage/dapp/services-payment.md
  builders/manage/dapp/xcm-channels.md
  builders/manage/developer-portal/impersonate.md
  builders/manage/developer-portal/maintenance.md
  builders/manage/developer-portal/minting.md
  builders/manage/developer-portal/pause-transactions.md
  builders/manage/developer-portal/sudo.md
  builders/manage/developer-portal/upgrade.md
  images/builders/manage/dapp/locate-registration-account.webp
  images/builders/manage/locate-sudo-account.webp
Labels: A2 - Maintenance Minor

#165 dApp guides - update screenshots
  images/builders/manage/dapp/services-payment/services-payment-2.webp
  images/builders/manage/dapp/services-payment/services-payment-3.webp
  images/builders/manage/dapp/token-management/token-management-3.webp
  images/builders/manage/dapp/token-management/token-management-4.webp
  images/builders/manage/dapp/token-management/token-management-5.webp
  images/builders/manage/dapp/token-management/token-management-6.webp
  images/builders/manage/dapp/token-management/token-management-7.webp
  images/builders/manage/dapp/token-management/token-management-8.webp
  images/builders/manage/dapp/xcm-channels/xcm-channels-3.webp
  images/builders/manage/dapp/xcm-channels/xcm-channels-4.webp
  images/builders/manage/dapp/xcm-channels/xcm-channels-5.webp
Labels: A2 - Maintenance Minor

#167 Adds RT700
  builders/manage/developer-portal/upgrade.md
Labels: A2 - Maintenance Minor

#168 Debt - Images cleanup
  builders/manage/dapp/manage-tokens.md
  builders/manage/dapp/services-payment.md
  builders/manage/dapp/xcm-channels.md
  images/builders/manage/dapp/services-payment/services-payment-1.webp
  images/builders/manage/dapp/services-payment/services-payment-2.webp
  images/builders/manage/dapp/services-payment/services-payment-3.webp
  images/builders/manage/dapp/token-management/token-management-1.webp
  images/builders/manage/dapp/token-management/token-management-2.webp
  images/builders/manage/dapp/token-management/token-management-3.webp
  images/builders/manage/dapp/token-management/token-management-4.webp
  images/builders/manage/dapp/token-management/token-management-5.webp
  images/builders/manage/dapp/token-management/token-management-6.webp
  images/builders/manage/dapp/token-management/token-management-7.webp
  images/builders/manage/dapp/token-management/token-management-8.webp
  images/builders/manage/dapp/xcm-channels/xcm-channels-1.webp
  images/builders/manage/dapp/xcm-channels/xcm-channels-2.webp
  images/builders/manage/dapp/xcm-channels/xcm-channels-3.webp
  images/builders/manage/dapp/xcm-channels/xcm-channels-4.webp
  images/builders/manage/dapp/xcm-channels/xcm-channels-5.webp
Labels: A2 - Maintenance Minor

#169 Smart contracts whitelist
  builders/manage/developer-portal/.pages
  builders/manage/developer-portal/smart-contracts-creation-filter.md
  images/builders/manage/developer-portal/smart-contracts-creation-filter/smart-contracts-creation-filter-1.webp
  images/builders/manage/developer-portal/smart-contracts-creation-filter/smart-contracts-creation-filter-2.webp
  images/builders/manage/developer-portal/smart-contracts-creation-filter/smart-contracts-creation-filter-3.webp
  images/builders/manage/developer-portal/smart-contracts-creation-filter/smart-contracts-creation-filter-4.webp
  images/index-pages/builders/manage/developer-portal/smart-contracts-creation-filter-dark.webp
  images/index-pages/builders/manage/developer-portal/smart-contracts-creation-filter.webp
Labels: A0 - New Content
