Repository moondance-labs/tanssi-docs, pull requests merged in 2024-03, with the labels that each got.

#109 Run a Collator using Docker - fix scripts
  .snippets/code/node-operators/block-producers/run-a-block-producer/block-producer-docker/terminal/pulling-docker-image.md
  .snippets/text/node-operators/block-producers/run-a-block-producer/docker-command.md
  node-operators/block-producers/onboarding/run-a-block-producer/block-producer-docker.md
Labels: A3 - Quick Fixes

#110 create block producer account set up docs
  .snippets/code/node-operators/block-producers/onboarding/account-setup/terminal/generate-session-keys.md
  .snippets/code/node-operators/block-producers/onboarding/run-a-block-producer/block-producer-docker/terminal/pulling-docker-image.md
  .snippets/text/node-operators/block-producers/onboarding/run-a-block-producer/docker-command.md
  .snippets/text/node-operators/block-producers/onboarding/run-a-block-producer/intro.md
  images/index-pages/node-operators/block-producers/onboarding/account-setup-dark.webp
  images/index-pages/node-operators/block-producers/onboarding/account-setup.webp
  images/node-operators/block-producers/onboarding/account-setup/setup-1.webp
  images/node-operators/block-producers/onboarding/account-setup/setup-2.webp
  images/node-operators/block-producers/onboarding/account-setup/setup-3.webp
  images/node-operators/block-producers/onboarding/account-setup/setup-4.webp
  images/node-operators/block-producers/onboarding/account-setup/setup-5.webp
  images/node-operators/block-producers/onboarding/account-setup/setup-6.webp
  images/node-operators/block-producers/onboarding/account-setup/setup-7.webp
  node-operators/block-producers/onboarding/.pages
  node-operators/block-producers/onboarding/account-setup.md
  node-operators/block-producers/onboarding/run-a-block-producer/block-producer-docker.md
  node-operators/block-producers/onboarding/run-a-block-producer/block-producer-systemd.md
  variables.yml
Labels: A0 - New Content

#90 [Chopsticks] Update repo & technical debt
  builders/interact/substrate-api/chopsticks.md
Labels: A2 - Maintenance Minor

#112 update commands for running a block producer
  .snippets/text/node-operators/block-producers/onboarding/run-a-block-producer/docker-command.md
  node-operators/block-producers/onboarding/run-a-block-producer/block-producer-systemd.md
Labels: A3 - Quick Fixes

#114 Apply formatting changes to the Acurast page
  builders/tooling/oracles/acurast.md
Labels: A3 - Quick Fixes

#113 update block producer configs (warp sync)
  .snippets/text/node-operators/block-producers/onboarding/run-a-block-producer/docker-command.md
  node-operators/block-producers/onboarding/run-a-block-producer/block-producer-systemd.md
Labels: A3 - Quick Fixes

#117 fix the systemd block producer name command
  node-operators/block-producers/onboarding/run-a-block-producer/block-producer-systemd.md
Labels: A3 - Quick Fixes

#111 general fixes
  builders/interact/ethereum-api/indexers/subsquid.md
  builders/interact/substrate-api/chopsticks.md
  builders/interact/substrate-api/indexers/subsquid.md
  builders/tooling/index.md
  builders/tooling/oracles/phala.md
Labels: A2 - Maintenance Minor

#124 session key to id
  node-operators/block-producers/onboarding/account-setup.md
Labels: A3 - Quick Fixes

#122 Reorganize Sudo Section
  builders/manage/.pages
  builders/manage/sudo.md
  builders/manage/sudo/.pages
  builders/manage/sudo/index.md
  builders/manage/sudo/minting.md
  builders/manage/sudo/sudo.md
  builders/manage/sudo/upgrade.md
  images/builders/manage/sudo/minting/minting-1.webp
  images/builders/manage/sudo/minting/minting-2.webp
  images/builders/manage/sudo/minting/minting-3.webp
  images/builders/manage/sudo/sudo-1.webp
  images/builders/manage/sudo/sudo-5.webp
  images/builders/manage/sudo/sudo-9.webp
  images/builders/manage/sudo/sudo/sudo-1.webp
  images/builders/manage/sudo/sudo/sudo-2.webp
  images/builders/manage/sudo/sudo/sudo-3.webp
  images/builders/manage/sudo/sudo/sudo-4.webp
  images/builders/manage/sudo/upgrade/upgrade-1.webp
  images/builders/manage/sudo/upgrade/upgrade-2.webp
  images/builders/manage/sudo/upgrade/upgrade-3.webp
  images/builders/manage/sudo/upgrade/upgrade-4.webp
  images/index-pages/builders/manage/sudo/minting-dark.webp
  images/index-pages/builders/manage/sudo/minting.webp
  images/index-pages/builders/manage/sudo/sudo-dark.webp
  images/index-pages/builders/manage/sudo/sudo.webp
  images/index-pages/builders/manage/sudo/upgrade-dark.webp
  images/index-pages/builders/manage/sudo/upgrade.webp
Labels: A1 - Maintenance Major

#118 adds Offboarding Docs
  images/index-pages/node-operators/block-producers/offboarding-dark.webp
  images/index-pages/node-operators/block-producers/offboarding.webp
  images/index-pages/node-operators/block-producers/offboarding/account-dark.webp
  images/index-pages/node-operators/block-producers/offboarding/account.webp
  images/node-operators/block-producers/offboarding/offboarding/offboarding-1.webp
  images/node-operators/block-producers/offboarding/offboarding/offboarding-2.webp
  images/node-operators/block-producers/offboarding/offboarding/offboarding-3.webp
  images/node-operators/block-producers/offboarding/offboarding/offboarding-4.webp
  images/node-operators/block-producers/offboarding/offboarding/offboarding-5.webp
  images/node-operators/block-producers/offboarding/offboarding/offboarding-6.webp
  images/node-operators/block-producers/offboarding/offboarding/offboarding-7.webp
  images/node-operators/block-producers/offboarding/offboarding/offboarding-8.webp
  node-operators/block-producers/.pages
  node-operators/block-producers/offboarding/.pages
  node-operators/block-producers/offboarding/account.md
  node-operators/block-producers/offboarding/index.md
  variables.yml
Labels: A0 - New Content

#129 DApp -> dApp
  builders/interact/ethereum-api/dev-env/hardhat.md
  learn/framework/architecture.md
  learn/tanssi/included-templates.md
  node-operators/appchain-node/rpc-docker.md
Labels: A3 - Quick Fixes

#126 [Builders-Templates] Moved the included modules section to overview
  builders/build/templates/evm.md
  builders/build/templates/overview.md
  builders/build/templates/substrate.md
Labels: A2 - Maintenance Minor

#127 EVM chain id registration requires RPC endpoint
  builders/deploy/dapp.md
Labels: A2 - Maintenance Minor

#115 Add Proxy Page for Block Producers
  images/index-pages/node-operators/block-producers/onboarding/proxy-accounts-dark.webp
  images/index-pages/node-operators/block-producers/onboarding/proxy-accounts.webp
  images/node-operators/block-producers/operational-tasks/proxy/proxy-block-1.webp
  images/node-operators/block-producers/operational-tasks/proxy/proxy-block-10.webp
  images/node-operators/block-producers/operational-tasks/proxy/proxy-block-11.webp
  images/node-operators/block-producers/operational-tasks/proxy/proxy-block-12.webp
  images/node-operators/block-producers/operational-tasks/proxy/proxy-block-13.webp
  images/node-operators/block-producers/operational-tasks/proxy/proxy-block-14.webp
  images/node-operators/block-producers/operational-tasks/proxy/proxy-block-2.webp
  images/node-operators/block-producers/operational-tasks/proxy/proxy-block-3.webp
  images/node-operators/block-producers/operational-tasks/proxy/proxy-block-4.webp
  images/node-operators/block-producers/operational-tasks/proxy/proxy-block-5.webp
  images/node-operators/block-producers/operational-tasks/proxy/proxy-block-6.webp
  images/node-operators/block-producers/operational-tasks/proxy/proxy-block-7.webp
  images/node-operators/block-producers/operational-tasks/proxy/proxy-block-8.webp
  images/node-operators/block-producers/operational-tasks/proxy/proxy-block-9.webp
  node-operators/block-producers/.pages
  node-operators/block-producers/onboarding/.pages
  node-operators/block-producers/onboarding/proxy-accounts.md
  node-operators/block-producers/operational-tasks/.pages
  node-operators/block-producers/operational-tasks/index.md
Labels: A0 - New Content

#131 Update Block Explorer Links
  .snippets/code/builders/interact/ethereum-api/libraries/viem/balances.ts
  .snippets/code/builders/interact/ethereum-api/libraries/viem/deploy.ts
  .snippets/code/builders/interact/ethereum-api/libraries/viem/get.ts
  .snippets/code/builders/interact/ethereum-api/libraries/viem/increment.ts
  .snippets/code/builders/interact/ethereum-api/libraries/viem/read-chain-data.ts
  .snippets/code/builders/interact/ethereum-api/libraries/viem/reset.ts
  .snippets/code/builders/interact/ethereum-api/libraries/viem/transaction.ts
  .snippets/code/builders/interact/ethereum-api/libraries/viem/write-chain-data.ts
  builders/interact/ethereum-api/dev-env/foundry.md
  builders/interact/ethereum-api/wallets/metamask.md
  builders/interact/ethereum-api/wallets/subwallet.md
  builders/interact/ethereum-api/wallets/talisman.md
  builders/tanssi-network/networks/dancebox/demo-evm-containerchain.md
  builders/tooling/oracles/acurast.md
  builders/tooling/oracles/phala.md
Labels: A2 - Maintenance Minor

#132 remove references to the proxy guide for now
  node-operators/block-producers/onboarding/proxy-accounts.md
Labels: A3 - Quick Fixes
