Repository moondance-labs/tanssi-docs, pull requests merged in 2024-07, with the labels that each got.

#170 Adding node key step for block producers
  .snippets/code/node-operators/block-producers/onboarding/run-a-block-producer/block-producer-docker/docker-command.md
  .snippets/text/node-operators/block-producers/onboarding/run-a-block-producer/generate-node-key-intro.md
  .snippets/text/node-operators/block-producers/onboarding/run-a-block-producer/generate-node-key-unsafe-note.md
  node-operators/block-producers/onboarding/run-a-block-producer/block-producer-docker.md
  node-operators/block-producers/onboarding/run-a-block-producer/block-producer-systemd.md
Labels: A2 - Maintenance Minor

#171 fix broken internal link
  builders/manage/developer-portal/pause-transactions.md
Labels: A3 - Quick Fixes

#172 Updated variables.yml "client_version: to v0.7.0 to be reflected in the onboarding doc pages
  variables.yml
Labels: A2 - Maintenance Minor

#157 XCM overview
  images/index-pages/learn/framework/xcm-dark.webp
  images/index-pages/learn/framework/xcm.webp
  images/learn/framework/xcm/dark-xcm-1.webp
  images/learn/framework/xcm/dark-xcm-2.webp
  images/learn/framework/xcm/dark-xcm-3.webp
  images/learn/framework/xcm/dark-xcm-4.webp
  images/learn/framework/xcm/light-xcm-1.webp
  images/learn/framework/xcm/light-xcm-2.webp
  images/learn/framework/xcm/light-xcm-3.webp
  images/learn/framework/xcm/light-xcm-4.webp
  learn/framework/.pages
  learn/framework/xcm.md
Labels: A0 - New Content

#173 Debt - Added references to learn section in the xcm channels dApp guide
  builders/manage/dapp/xcm-channels.md
Labels: A2 - Maintenance Minor

#175 fix typo
  builders/tanssi-network/testnet/demo-evm-appchain.md
Labels: A3 - Quick Fixes
