Repository moondance-labs/tanssi-docs, pull requests merged in 2024-05, with the labels that each got.

#89 Adds Batch Page to Precompiles
  .snippets/code/dapp-developers/developer-toolkit/ethereum-api/precompiles/batch/batch.sol
  .snippets/code/dapp-developers/developer-toolkit/ethereum-api/precompiles/batch/ethers-batch.js
  .snippets/code/dapp-developers/developer-toolkit/ethereum-api/precompiles/batch/simple-contract.sol
  .snippets/code/dapp-developers/developer-toolkit/ethereum-api/precompiles/batch/web3js-batch.js
  .snippets/code/dapp-developers/developer-toolkit/ethereum-api/precompiles/batch/web3py-batch.py
  builders/toolkit/ethereum-api/.pages
  builders/toolkit/ethereum-api/precompiles/.pages
  builders/toolkit/ethereum-api/precompiles/batch.md
  builders/toolkit/ethereum-api/precompiles/index.md
  images/dapp-developers/developer-toolkit/ethereum-api/precompiles/batch/batch-1.webp
  images/dapp-developers/developer-toolkit/ethereum-api/precompiles/batch/batch-2.webp
  images/dapp-developers/developer-toolkit/ethereum-api/precompiles/batch/batch-3.webp
  images/dapp-developers/developer-toolkit/ethereum-api/precompiles/batch/batch-4.webp
  images/dapp-developers/developer-toolkit/ethereum-api/precompiles/batch/batch-5.webp
  images/dapp-developers/developer-toolkit/ethereum-api/precompiles/batch/batch-6.webp
  images/dapp-developers/developer-toolkit/ethereum-api/precompiles/batch/batch-7.webp
  images/index-pages/builders/toolkit/ethereum-api/precompiles-dark.webp
  images/index-pages/builders/toolkit/ethereum-api/precompiles.webp
  images/index-pages/builders/toolkit/ethereum-api/precompiles/batch-dark.webp
  images/index-pages/builders/toolkit/ethereum-api/precompiles/batch.webp
  variables.yml
Labels: A0 - New Content

#137 Revise hardhat to use Ignition modules
  .snippets/code/builders/toolkit/ethereum-api/dev-env/hardhat/Box.js
  .snippets/code/builders/toolkit/ethereum-api/dev-env/hardhat/terminal/compile.md
  .snippets/code/builders/toolkit/ethereum-api/dev-env/hardhat/terminal/create.md
  .snippets/code/builders/toolkit/ethereum-api/dev-env/hardhat/terminal/deploy.md
  .snippets/code/builders/toolkit/ethereum-api/dev-env/hardhat/terminal/interact.md
  builders/toolkit/ethereum-api/dev-env/.pages
  builders/toolkit/ethereum-api/dev-env/hardhat.md
Labels: A2 - Maintenance Minor

#138 Add Docs for Establishing an Identity
  builders/.pages
  builders/account-management/.pages
  builders/account-management/identity.md
  builders/account-management/index.md
  images/builders/account-management/identity/identity-1.webp
  images/builders/account-management/identity/identity-2.webp
  images/builders/account-management/identity/identity-3.webp
  images/builders/account-management/identity/identity-4.webp
  images/builders/account-management/identity/identity-5.webp
  images/builders/account-management/identity/identity-6.webp
  images/builders/account-management/identity/identity-7.webp
  images/builders/account-management/identity/identity-8.webp
  images/builders/account-management/identity/identity-9.webp
  images/index-pages/builders/account-management-dark.webp
  images/index-pages/builders/account-management.webp
  images/index-pages/builders/account-management/identity-dark.webp
  images/index-pages/builders/account-management/identity.webp
  variables.yml
Labels: A0 - New Content

#91 Adds Native Token Precompile Page
  .snippets/code/builders/toolkit/ethereum-api/precompiles/batch/batch.sol
  .snippets/code/builders/toolkit/ethereum-api/precompiles/batch/ethers-batch.js
  .snippets/code/builders/toolkit/ethereum-api/precompiles/batch/simple-contract.sol
  .snippets/code/builders/toolkit/ethereum-api/precompiles/batch/web3js-batch.js
  .snippets/code/builders/toolkit/ethereum-api/precompiles/batch/web3py-batch.py
  .snippets/code/builders/toolkit/ethereum-api/precompiles/erc20/erc20.sol
  builders/toolkit/ethereum-api/precompiles/.pages
  builders/toolkit/ethereum-api/precompiles/batch.md
  builders/toolkit/ethereum-api/precompiles/erc20.md
  images/builders/toolkit/ethereum-api/precompiles/batch/batch-1.webp
  images/builders/toolkit/ethereum-api/precompiles/batch/batch-2.webp
  images/builders/toolkit/ethereum-api/precompiles/batch/batch-3.webp
  images/builders/toolkit/ethereum-api/precompiles/batch/batch-4.webp
  images/builders/toolkit/ethereum-api/precompiles/batch/batch-5.webp
  images/builders/toolkit/ethereum-api/precompiles/batch/batch-6.webp
  images/builders/toolkit/ethereum-api/precompiles/batch/batch-7.webp
  images/builders/toolkit/ethereum-api/precompiles/erc20/erc-1.webp
  images/builders/toolkit/ethereum-api/precompiles/erc20/erc-10.webp
  images/builders/toolkit/ethereum-api/precompiles/erc20/erc-11.webp
  images/builders/toolkit/ethereum-api/precompiles/erc20/erc-12.webp
  images/builders/toolkit/ethereum-api/precompiles/erc20/erc-13.webp
  images/builders/toolkit/ethereum-api/precompiles/erc20/erc-2.webp
  images/builders/toolkit/ethereum-api/precompiles/erc20/erc-3.webp
  images/builders/toolkit/ethereum-api/precompiles/erc20/erc-4.webp
  images/builders/toolkit/ethereum-api/precompiles/erc20/erc-5.webp
  images/builders/toolkit/ethereum-api/precompiles/erc20/erc-6.webp
  images/builders/toolkit/ethereum-api/precompiles/erc20/erc-7.webp
  images/builders/toolkit/ethereum-api/precompiles/erc20/erc-8.webp
  images/builders/toolkit/ethereum-api/precompiles/erc20/erc-9.webp
  images/index-pages/builders/toolkit/ethereum-api/precompiles/erc20-dark.webp
  images/index-pages/builders/toolkit/ethereum-api/precompiles/erc20.webp
  variables.yml
Labels: A0 - New Content

#123 Add Proxy Page in Learn Section
  builders/account-management/.pages
  builders/account-management/proxy-accounts.md
  images/builders/account-management/proxy/proxy-1.webp
  images/builders/account-management/proxy/proxy-10.webp
  images/builders/account-management/proxy/proxy-11.webp
  images/builders/account-management/proxy/proxy-12.webp
  images/builders/account-management/proxy/proxy-13.webp
  images/builders/account-management/proxy/proxy-2.webp
  images/builders/account-management/proxy/proxy-3.webp
  images/builders/account-management/proxy/proxy-4.webp
  images/builders/account-management/proxy/proxy-5.webp
  images/builders/account-management/proxy/proxy-6.webp
  images/builders/account-management/proxy/proxy-7.webp
  images/builders/account-management/proxy/proxy-8.webp
  images/builders/account-management/proxy/proxy-9.webp
  images/index-pages/builders/account-management/proxy-accounts-dark.webp
  images/index-pages/builders/account-management/proxy-accounts.webp
Labels: A0 - New Content

#144 runtime upgrade - wasm file references
  builders/manage/sudo/upgrade.md
  builders/toolkit/substrate-api/dev-env/chopsticks.md
  images/builders/manage/sudo/sudo/sudo-1.webp
  learn/appchains/runtime-features.md
Labels: A2 - Maintenance Minor

#147 Apply some minor fixes to the precompile pages
  builders/toolkit/ethereum-api/precompiles/batch.md
  builders/toolkit/ethereum-api/precompiles/erc20.md
  images/index-pages/builders/toolkit/ethereum-api/precompiles-dark.webp
  images/index-pages/builders/toolkit/ethereum-api/precompiles.webp
  images/index-pages/builders/toolkit/ethereum-api/precompiles/batch-dark.webp
  images/index-pages/builders/toolkit/ethereum-api/precompiles/batch.webp
  images/index-pages/builders/toolkit/ethereum-api/precompiles/erc20-dark.webp
  images/index-pages/builders/toolkit/ethereum-api/precompiles/erc20.webp
Labels: A2 - Maintenance Minor

#149 update broken links
  builders/account-management/identity.md
  learn/tanssi/technical-features.md
Labels: A3 - Quick Fixes

#148 Manage - Sudo - Transaction pause
  builders/manage/sudo/.pages
  builders/manage/sudo/pause-transactions.md
  images/builders/manage/sudo/pause-transactions/pause-transactions-1.webp
  images/builders/manage/sudo/pause-transactions/pause-transactions-2.webp
  images/builders/manage/sudo/pause-transactions/pause-transactions-3.webp
  images/builders/manage/sudo/pause-transactions/pause-transactions-4.webp
  images/index-pages/builders/manage/sudo/pause-transactions-dark.webp
  images/index-pages/builders/manage/sudo/pause-transactions.webp
Labels: A0 - New Content

#150 Updates block time & aligns session time
  learn/tanssi/technical-features.md
  variables.yml
Labels: A2 - Maintenance Minor, A3 - Quick Fixes

#151 link cleanup
  .snippets/text/_common/general-js-tutorial-check.md
  .snippets/text/node-operators/installing-docker.md
  .snippets/text/node-operators/optimized-binaries-note.md
  CONTRIBUTING.md
  README.md
  builders/build/customize/adding-built-in-module.md
  builders/build/customize/adding-custom-made-module.md
  builders/build/customize/adding-external-module.md
  builders/build/customize/customizing-chain-specs.md
  builders/build/customize/prerequisites.md
  builders/build/templates/custom-runtime.md
  builders/build/templates/evm.md
  builders/build/templates/overview.md
  builders/deploy/dapp.md
  builders/manage/sudo/impersonate.md
  builders/manage/sudo/maintenance.md
  builders/manage/sudo/minting.md
  builders/manage/sudo/pause-transactions.md
  builders/manage/sudo/sudo.md
  builders/manage/sudo/upgrade.md
  builders/tanssi-network/testnet/dancebox.md
  builders/tanssi-network/testnet/demo-evm-appchain.md
  builders/toolkit/ethereum-api/dev-env/foundry.md
  builders/toolkit/ethereum-api/dev-env/hardhat.md
  builders/toolkit/ethereum-api/dev-env/remix.md
  builders/toolkit/ethereum-api/libraries/ethersjs.md
  builders/toolkit/ethereum-api/libraries/viem.md
  builders/toolkit/ethereum-api/libraries/web3js.md
  builders/toolkit/ethereum-api/libraries/web3py.md
  builders/toolkit/ethereum-api/precompiles/batch.md
  builders/toolkit/ethereum-api/precompiles/erc20.md
  builders/toolkit/ethereum-api/wallets/metamask.md
  builders/toolkit/ethereum-api/wallets/subwallet.md
  builders/toolkit/ethereum-api/wallets/talisman.md
  builders/toolkit/integrations/indexers/subsquid/erc20-transfers.md
  builders/toolkit/integrations/indexers/subsquid/quick-start.md
  builders/toolkit/integrations/oracles/acurast.md
  builders/toolkit/integrations/oracles/phala.md
  builders/toolkit/substrate-api/dev-env/chopsticks.md
  builders/toolkit/substrate-api/libraries/polkadot-js-api.md
  builders/toolkit/substrate-api/libraries/sidecar-api.md
  builders/toolkit/substrate-api/wallets/subwallet.md
  builders/toolkit/substrate-api/wallets/talisman.md
  images/__index-page-icon-template.svg
  learn/appchains/overview.md
  learn/appchains/runtime-features.md
  learn/appchains/tx-fees.md
  learn/framework/architecture.md
  learn/framework/modules.md
  learn/framework/overview.md
  learn/tanssi/included-templates.md
  learn/tanssi/overview.md
  learn/tanssi/technical-features.md
  node-operators/appchain-node/rpc-docker.md
  node-operators/appchain-node/rpc-systemd.md
  node-operators/block-producers/onboarding/run-a-block-producer/block-producer-docker.md
  node-operators/block-producers/onboarding/run-a-block-producer/block-producer-systemd.md
  node-operators/block-producers/operational-tasks/proxy-accounts.md
  node-operators/block-producers/operational-tasks/upgrade-your-node/upgrade-docker.md
  node-operators/block-producers/operational-tasks/upgrade-your-node/upgrade-systemd.md
Labels: A2 - Maintenance Minor

#93 Adds Docs for the Call Permit Precompile
  .snippets/code/builders/toolkit/ethereum-api/precompiles/call-permit/call-permit.sol
  .snippets/code/builders/toolkit/ethereum-api/precompiles/call-permit/getSignature.js
  .snippets/code/builders/toolkit/ethereum-api/precompiles/call-permit/set-message.sol
  builders/toolkit/ethereum-api/precompiles/.pages
  builders/toolkit/ethereum-api/precompiles/call-permit.md
  images/builders/toolkit/ethereum-api/precompiles/call-permit/call-1.webp
  images/builders/toolkit/ethereum-api/precompiles/call-permit/call-2.webp
  images/builders/toolkit/ethereum-api/precompiles/call-permit/call-3.webp
  images/builders/toolkit/ethereum-api/precompiles/call-permit/call-4.webp
  images/builders/toolkit/ethereum-api/precompiles/call-permit/call-5.webp
  images/builders/toolkit/ethereum-api/precompiles/call-permit/call-6.webp
  images/builders/toolkit/ethereum-api/precompiles/call-permit/call-7.webp
  images/builders/toolkit/ethereum-api/precompiles/call-permit/call-8.webp
  images/builders/toolkit/ethereum-api/precompiles/call-permit/call-9.webp
  images/index-pages/builders/toolkit/ethereum-api/precompiles/call-permit-dark.webp
  images/index-pages/builders/toolkit/ethereum-api/precompiles/call-permit.webp
  variables.yml
Labels: A0 - New Content

#152 fix 404s
  builders/build/templates/custom-runtime.md
  builders/build/templates/overview.md
Labels: A2 - Maintenance Minor
