Repository moondance-labs/tanssi-docs, pull requests merged in 2024-02, with the labels that each got.

#87 Add Content for Manage your AppChain
  builders/.pages
  builders/manage/.pages
  builders/manage/index.md
  builders/manage/sudo.md
  images/builders/manage/sudo/sudo-1.webp
  images/builders/manage/sudo/sudo-2.webp
  images/builders/manage/sudo/sudo-3.webp
  images/builders/manage/sudo/sudo-4.webp
  images/builders/manage/sudo/sudo-5.webp
  images/builders/manage/sudo/sudo-6.webp
  images/builders/manage/sudo/sudo-7.webp
  images/builders/manage/sudo/sudo-8.webp
  images/builders/manage/sudo/sudo-9.webp
  images/index-pages/builders/manage-dark.webp
  images/index-pages/builders/manage.webp
  images/index-pages/builders/manage/sudo-dark.webp
  images/index-pages/builders/manage/sudo.webp
Labels: A0 - New Content

#92 update manage section icons and sudo page title on left nav
  builders/manage/.pages
  builders/manage/sudo.md
  images/index-pages/builders/manage-dark.webp
  images/index-pages/builders/manage.webp
  images/index-pages/builders/manage/sudo-dark.webp
  images/index-pages/builders/manage/sudo.webp
Labels: A3 - Quick Fixes

#94 Add a page for Appchain Tx Fees
  images/index-pages/learn/appchains/tx-fees-dark.png
  images/index-pages/learn/appchains/tx-fees.png
  learn/appchains/.pages
  learn/appchains/tx-fees.md
  variables.yml
Labels: A0 - New Content

#97 convert images to webp
  images/builders/interact/substrate-api/chopsticks/chopsticks-1.png
  images/builders/interact/substrate-api/chopsticks/chopsticks-1.webp
  images/index-pages/builders/interact/substrate-api/chopsticks-dark.png
  images/index-pages/builders/interact/substrate-api/chopsticks-dark.webp
  images/index-pages/builders/interact/substrate-api/chopsticks.png
  images/index-pages/builders/interact/substrate-api/chopsticks.webp
  images/index-pages/learn/appchains/tx-fees-dark.png
  images/index-pages/learn/appchains/tx-fees-dark.webp
  images/index-pages/learn/appchains/tx-fees.png
  images/index-pages/learn/appchains/tx-fees.webp
Labels: A3 - Quick Fixes

#98 Update Default Block Explorers
  .snippets/code/builders/interact/ethereum-api/libraries/viem/balances.ts
  .snippets/code/builders/interact/ethereum-api/libraries/viem/deploy.ts
  .snippets/code/builders/interact/ethereum-api/libraries/viem/get.ts
  .snippets/code/builders/interact/ethereum-api/libraries/viem/increment.ts
  .snippets/code/builders/interact/ethereum-api/libraries/viem/read-chain-data.ts
  .snippets/code/builders/interact/ethereum-api/libraries/viem/reset.ts
  .snippets/code/builders/interact/ethereum-api/libraries/viem/transaction.ts
  .snippets/code/builders/interact/ethereum-api/libraries/viem/write-chain-data.ts
  builders/interact/ethereum-api/dev-env/foundry.md
  builders/interact/ethereum-api/dev-env/remix.md
  builders/interact/ethereum-api/wallets/metamask.md
  builders/interact/ethereum-api/wallets/subwallet.md
  builders/interact/ethereum-api/wallets/talisman.md
  builders/tanssi-network/networks/dancebox/demo-evm-containerchain.md
Labels: A2 - Maintenance Minor

#95 Adds Node Operator - Running an RPC endpoint
  .pages
  .snippets/code/node-operators/rpc/terminal/hello-world.md
  .snippets/code/node-operators/rpc/terminal/pulling-docker-image.md
  .snippets/code/node-operators/rpc/terminal/syncing-process.md
  images/index-pages/node-operators/appchain-node-dark.webp
  images/index-pages/node-operators/appchain-node.webp
  images/index-pages/node-operators/appchain-node/rpc-docker-dark.webp
  images/index-pages/node-operators/appchain-node/rpc-docker.webp
  images/node-operators/rpc/rpc-1.webp
  node-operators/.pages
  node-operators/appchain-node/.pages
  node-operators/appchain-node/index.md
  node-operators/appchain-node/rpc-docker.md
  node-operators/index.md
Labels: A0 - New Content

#99 Update Unit to TANGO
  .snippets/code/builders/interact/ethereum-api/libraries/ethers/terminal/balances.md
  .snippets/code/builders/interact/ethereum-api/libraries/ethers/terminal/transaction.md
  .snippets/code/builders/interact/ethereum-api/libraries/ethersjs/balances.js
  .snippets/code/builders/interact/ethereum-api/libraries/viem/balances.ts
  .snippets/code/builders/interact/ethereum-api/libraries/viem/deploy.ts
  .snippets/code/builders/interact/ethereum-api/libraries/viem/get.ts
  .snippets/code/builders/interact/ethereum-api/libraries/viem/increment.ts
  .snippets/code/builders/interact/ethereum-api/libraries/viem/read-chain-data.ts
  .snippets/code/builders/interact/ethereum-api/libraries/viem/reset.ts
  .snippets/code/builders/interact/ethereum-api/libraries/viem/transaction.ts
  .snippets/code/builders/interact/ethereum-api/libraries/viem/write-chain-data.ts
  .snippets/code/builders/interact/ethereum-api/libraries/web3js/balances.js
  .snippets/code/builders/interact/ethereum-api/libraries/web3py/balances.py
  builders/deploy/dapp.md
  builders/interact/ethereum-api/libraries/ethersjs.md
  builders/interact/ethereum-api/libraries/viem.md
  builders/interact/ethereum-api/libraries/web3js.md
  builders/interact/ethereum-api/libraries/web3py.md
Labels: A2 - Maintenance Minor

#96 Add Phala Price Feeds Docs
  .snippets/code/builders/tooling/indexers/subsquid/MyTok.sol
  .snippets/code/builders/tooling/indexers/subsquid/deploy.js
  .snippets/code/builders/tooling/indexers/subsquid/erc20.json
  .snippets/code/builders/tooling/indexers/subsquid/hardhat-config.js
  .snippets/code/builders/tooling/indexers/subsquid/main-with-logging.ts
  .snippets/code/builders/tooling/indexers/subsquid/main.ts
  .snippets/code/builders/tooling/indexers/subsquid/processor.ts
  .snippets/code/builders/tooling/indexers/subsquid/sample-query.graphql
  .snippets/code/builders/tooling/indexers/subsquid/schema.graphql
  .snippets/code/builders/tooling/indexers/subsquid/transactions.js
  .snippets/code/builders/tooling/oracles/phala/AggregatorV3Interface.sol
  .snippets/code/builders/tooling/oracles/phala/OffchainAggregator.s.sol
  .snippets/code/builders/tooling/oracles/phala/define-chain.ts
  .snippets/code/builders/tooling/oracles/phala/env.txt
  .snippets/code/builders/tooling/oracles/phala/feeder.ts
  .snippets/code/builders/tooling/oracles/phala/terminal/build.md
  .snippets/code/builders/tooling/oracles/phala/terminal/deploy.md
  .snippets/code/builders/tooling/oracles/phala/terminal/update.md
  builders/.pages
  builders/tooling/.pages
  builders/tooling/index.md
  builders/tooling/indexers/.pages
  builders/tooling/indexers/index.md
  builders/tooling/indexers/subsquid.md
  builders/tooling/oracles/.pages
  builders/tooling/oracles/index.md
  builders/tooling/oracles/phala.md
  builders/tutorials/.pages
  images/builders/tooling/indexers/subsquid/subsquid-1.webp
  images/builders/tooling/indexers/subsquid/subsquid-2.webp
  images/builders/tooling/indexers/subsquid/subsquid-3.webp
  images/builders/tooling/indexers/subsquid/subsquid-4.webp
  images/builders/tooling/indexers/subsquid/subsquid-5.webp
  images/builders/tooling/oracles/phala/phala-1.webp
  images/builders/tooling/oracles/phala/phala-2.webp
  images/builders/tooling/oracles/phala/phala-3.webp
  images/builders/tooling/oracles/phala/phala-4.webp
  images/builders/tooling/oracles/phala/phala-5.webp
  images/builders/tooling/oracles/phala/phala-6.webp
  images/index-pages/builders/tooling-dark.webp
  images/index-pages/builders/tooling.webp
  images/index-pages/builders/tooling/indexers-dark.webp
  images/index-pages/builders/tooling/indexers.webp
  images/index-pages/builders/tooling/indexers/subsquid-dark.webp
  images/index-pages/builders/tooling/indexers/subsquid.webp
  images/index-pages/builders/tooling/oracles-dark.webp
  images/index-pages/builders/tooling/oracles.webp
  images/index-pages/builders/tooling/oracles/phala-dark.webp
  images/index-pages/builders/tooling/oracles/phala.webp
  images/index-pages/builders/tutorials-dark.webp
  images/index-pages/builders/tutorials.webp
  variables.yml
Labels: A0 - New Content

#103 Acurast Price Feed Docs
  .snippets/code/builders/tooling/oracles/acurast/AcurastScript.js
  .snippets/code/builders/tooling/oracles/acurast/AggregatorV3Interface.sol
  .snippets/code/builders/tooling/oracles/acurast/InsecureDummyPriceFeed.sol
  .snippets/code/builders/tooling/oracles/acurast/terminal/api.md
  builders/tooling/oracles/.pages
  builders/tooling/oracles/acurast.md
  images/builders/tooling/oracles/acurast/acurast-1.webp
  images/builders/tooling/oracles/acurast/acurast-2.webp
  images/builders/tooling/oracles/acurast/acurast-3.webp
  images/builders/tooling/oracles/acurast/acurast-4.webp
  images/builders/tooling/oracles/acurast/acurast-5.webp
  images/index-pages/builders/tooling/oracles/acurast-dark.webp
  images/index-pages/builders/tooling/oracles/acurast.webp
Labels: A0 - New Content

#104 Adds running an RPC using systemd article
  .snippets/code/node-operators/appchain-node/rpc-docker/terminal/hello-world.md
  .snippets/code/node-operators/appchain-node/rpc-docker/terminal/pulling-docker-image.md
  .snippets/code/node-operators/appchain-node/rpc-docker/terminal/syncing-process.md
  .snippets/code/node-operators/appchain-node/rpc-systemd/terminal/check-status.md
  .snippets/code/node-operators/appchain-node/rpc-systemd/terminal/journalctl-logs.md
  .snippets/text/node-operators/appchain-node/bootnode-item.md
  .snippets/text/node-operators/appchain-node/fetching-bootnode-section.md
  .snippets/text/node-operators/appchain-node/intro.md
  .snippets/text/node-operators/appchain-node/run-flags.md
  images/index-pages/node-operators/appchain-node/rpc-systemd-dark.webp
  images/index-pages/node-operators/appchain-node/rpc-systemd.webp
  images/node-operators/appchain-node/rpc-docker-systemd-1.webp
  images/node-operators/appchain-node/rpc-systemd/rpc-systemd-1.webp
  images/node-operators/rpc/rpc-1.webp
  node-operators/appchain-node/.pages
  node-operators/appchain-node/rpc-docker.md
  node-operators/appchain-node/rpc-systemd.md
Labels: A0 - New Content

#105 Adds Faucet information for Demo EVM AppChain
  builders/interact/ethereum-api/wallets/metamask.md
  builders/tanssi-network/networks/dancebox/demo-evm-containerchain.md
  builders/tooling/oracles/acurast.md
  images/builders/network/networks/dancebox/demo/demo-1.webp
  images/builders/network/networks/dancebox/demo/demo-2.webp
Labels: A0 - New Content

#108 Add Acurast Price Feeds on Demo EVM Appchain
  builders/tooling/oracles/acurast.md
  variables.yml
Labels: A2 - Maintenance Minor

#106 Adds how to run a collator using docker & system
  .snippets/code/node-operators/block-producers/run-a-block-producer/block-producer-docker/terminal/pulling-docker-image.md
  .snippets/code/node-operators/terminal/hello-world.md
  .snippets/code/node-operators/terminal/syncing-process.md
  .snippets/text/node-operators/appchain-node/docker-command.md
  .snippets/text/node-operators/block-producers/run-a-block-producer/docker-command.md
  .snippets/text/node-operators/block-producers/run-a-block-producer/intro.md
  .snippets/text/node-operators/installing-docker.md
  .snippets/text/node-operators/optimized-binaries-note.md
  images/index-pages/node-operators/block-producers-dark.webp
  images/index-pages/node-operators/block-producers.webp
  images/index-pages/node-operators/block-producers/onboarding-dark.webp
  images/index-pages/node-operators/block-producers/onboarding.webp
  images/index-pages/node-operators/block-producers/onboarding/run-a-block-producer-dark.webp
  images/index-pages/node-operators/block-producers/onboarding/run-a-block-producer.webp
  images/index-pages/node-operators/block-producers/onboarding/run-a-block-producer/block-producer-docker-dark.webp
  images/index-pages/node-operators/block-producers/onboarding/run-a-block-producer/block-producer-docker.webp
  images/index-pages/node-operators/block-producers/onboarding/run-a-block-producer/block-producer-systemd-dark.webp
  images/index-pages/node-operators/block-producers/onboarding/run-a-block-producer/block-producer-systemd.webp
  node-operators/.pages
  node-operators/appchain-node/rpc-docker.md
  node-operators/appchain-node/rpc-systemd.md
  node-operators/block-producers/.pages
  node-operators/block-producers/index.md
  node-operators/block-producers/onboarding/.pages
  node-operators/block-producers/onboarding/index.md
  node-operators/block-producers/onboarding/run-a-block-producer/.pages
  node-operators/block-producers/onboarding/run-a-block-producer/block-producer-docker.md
  node-operators/block-producers/onboarding/run-a-block-producer/block-producer-systemd.md
  node-operators/block-producers/onboarding/run-a-block-producer/index.md
  variables.yml
Labels: A0 - New Content
