Repository moondance-labs/tanssi-docs, pull requests merged in 2025-04, with the labels that each got.

#245 Upgrade validators - systemd
  .snippets/text/node-operators/github-release-notifications.md
  llms.txt
  node-operators/sequencers/operational-tasks/upgrade-your-node/index.md
  node-operators/sequencers/operational-tasks/upgrade-your-node/upgrade-docker.md
  node-operators/sequencers/operational-tasks/upgrade-your-node/upgrade-systemd.md
  node-operators/validators/.pages
  node-operators/validators/operational-tasks/.pages
  node-operators/validators/operational-tasks/index.md
  node-operators/validators/operational-tasks/upgrade-your-node/.pages
  node-operators/validators/operational-tasks/upgrade-your-node/index.md
  node-operators/validators/operational-tasks/upgrade-your-node/upgrade-systemd.md
Labels: A0 - New Content, B1 - Ready to Merge

#253 Several hot fixes for onboarding operators docs
  .snippets/code/node-operators/validators/onboarding/run-a-validator/validators-docker/docker-command.md
  .snippets/code/node-operators/validators/onboarding/run-a-validator/validators-docker/terminal/pulling-docker-image.md
  llms.txt
  node-operators/validators/onboarding/opt-in-to-tanssi.md
  node-operators/validators/onboarding/run-a-validator/validators-systemd.md
  variables.yml
Labels: A3 - Quick Fixes, B1 - Ready to Merge, C2 - High

#250 Setup validator account
  .snippets/code/node-operators/validators/onboarding/account-setup/terminal/generate-session-keys.md
  images/node-operators/validators/onboarding/account-setup/account-setup-1.webp
  images/node-operators/validators/onboarding/account-setup/account-setup-2.webp
  llms.txt
  node-operators/validators/onboarding/.pages
  node-operators/validators/onboarding/account-setup.md
  variables.yml
Labels: A0 - New Content, B1 - Ready to Merge, C2 - High

#249 Upgrade a validator - docker version
  .snippets/code/node-operators/validators/operational-tasks/upgrade-your-node/upgrade-docker/terminal/docker-stop.md
  llms.txt
  node-operators/sequencers/operational-tasks/upgrade-your-node/upgrade-docker.md
  node-operators/validators/onboarding/run-a-validator/validators-docker.md
  node-operators/validators/operational-tasks/upgrade-your-node/.pages
  node-operators/validators/operational-tasks/upgrade-your-node/upgrade-docker.md
  node-operators/validators/operational-tasks/upgrade-your-node/upgrade-systemd.md
Labels: A0 - New Content, B1 - Ready to Merge, C2 - High

#255 fix: remove unnecesary flags in the start command
  .snippets/code/node-operators/validators/onboarding/run-a-validator/validators-docker/docker-command.md
  llms.txt
  node-operators/validators/onboarding/run-a-validator/validators-systemd.md
Labels: A3 - Quick Fixes, B0 - Needs Review, C2 - High

#256 fixes sequecers binary release
  llms.txt
  node-operators/sequencers/onboarding/run-a-sequencer/sequencers-systemd.md
  node-operators/sequencers/operational-tasks/upgrade-your-node/upgrade-systemd.md
  variables.yml
Labels: A3 - Quick Fixes

#254 Set up operator proxies
  images/node-operators/validators/operational-tasks/proxy-accounts/proxy-accounts-1.webp
  images/node-operators/validators/operational-tasks/proxy-accounts/proxy-accounts-2.webp
  images/node-operators/validators/operational-tasks/proxy-accounts/proxy-accounts-3.webp
  images/node-operators/validators/operational-tasks/proxy-accounts/proxy-accounts-4.webp
  images/node-operators/validators/operational-tasks/proxy-accounts/proxy-accounts-5.webp
  images/node-operators/validators/operational-tasks/proxy-accounts/proxy-accounts-6.webp
  images/node-operators/validators/operational-tasks/proxy-accounts/proxy-accounts-7.webp
  images/node-operators/validators/operational-tasks/proxy-accounts/proxy-accounts-8.webp
  llms.txt
  node-operators/validators/operational-tasks/.pages
  node-operators/validators/operational-tasks/proxy-accounts.md
Labels: A0 - New Content, B1 - Ready to Merge

#259 Timeline for onboarding operators
  .snippets/text/node-operators/validators/onboarding/onboarding-timeline.json
  llms.txt
  node-operators/validators/onboarding/index.md
Labels: A1 - Maintenance Major, B1 - Ready to Merge, C1 - Medium
