Repository moondance-labs/tanssi-docs, pull requests merged in 2025-03, with the labels that each got.

#238 Update Ubuntu in Workflow
  .github/workflows/check-mkdocs-build.yml
Labels: A2 - Maintenance Minor, B1 - Ready to Merge, C2 - High

#231 docs: symbiotic revision
  learn/tanssi/external-security-providers/symbiotic.md
  llms.txt
Labels: A1 - Maintenance Major, B1 - Ready to Merge

#235 docs: Tanssi - Ethereum communication
  learn/tanssi/external-security-providers/symbiotic.md
  llms.txt
Labels: A0 - New Content, B1 - Ready to Merge

#239 feat: vault section enhancement
  learn/tanssi/external-security-providers/symbiotic.md
  llms.txt
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#240 remove unnecessary styling
  builders/build/customize/index.md
  builders/build/index.md
  builders/toolkit/ethereum-api/precompiles/index.md
  llms.txt
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#241 Semrush march report
  learn/tanssi/external-security-providers/symbiotic.md
  llms.txt
Labels: A2 - Maintenance Minor, B1 - Ready to Merge, C1 - Medium

#228 Network nodes - RPC & Archive
  .snippets/code/node-operators/network-node/rpc-docker/docker-command.md
  .snippets/text/node-operators/network-node/fetching-bootnode-section.md
  .snippets/text/node-operators/network-node/run-flags.md
  images/node-operators/network-node/rpc-systemd/rpc-systemd-1.webp
  llms.txt
  node-operators/network-node/index.md
  node-operators/network-node/rpc-docker.md
  node-operators/network-node/rpc-systemd.md
Labels: A1 - Maintenance Major, B1 - Ready to Merge, C2 - High

#230 Validators (operators) using systemd
  .snippets/code/node-operators/terminal/check-landlock.md
  .snippets/code/node-operators/validators/onboarding/run-a-validator/validators-docker/docker-command.md
  .snippets/code/node-operators/validators/onboarding/run-a-validator/validators-docker/terminal/pulling-docker-image.md
  .snippets/text/node-operators/optimized-binaries-note.md
  .snippets/text/node-operators/validators/onboarding/run-a-validator/intro.md
  llms.txt
  node-operators/.pages
  node-operators/index.md
  node-operators/validators/.pages
  node-operators/validators/index.md
  node-operators/validators/onboarding/.pages
  node-operators/validators/onboarding/index.md
  node-operators/validators/onboarding/run-a-validator/.pages
  node-operators/validators/onboarding/run-a-validator/index.md
  node-operators/validators/onboarding/run-a-validator/validators-docker.md
  node-operators/validators/onboarding/run-a-validator/validators-systemd.md
  variables.yml
Labels: A0 - New Content, B1 - Ready to Merge

#237 Registering in Symbiotic & Opting In
  .snippets/text/node-operators/validators/onboarding/run-a-validator/intro.md
  .snippets/text/node-operators/validators/onboarding/run-a-validator/prerequisites.md
  images/node-operators/validators/onboarding/opt-in-to-tanssi/opt-in-to-tanssi-1.webp
  images/node-operators/validators/onboarding/opt-in-to-tanssi/opt-in-to-tanssi-2.webp
  images/node-operators/validators/onboarding/opt-in-to-tanssi/opt-in-to-tanssi-3.webp
  images/node-operators/validators/onboarding/opt-in-to-tanssi/opt-in-to-tanssi-4.webp
  images/node-operators/validators/onboarding/opt-in-to-tanssi/opt-in-to-tanssi-5.webp
  images/node-operators/validators/onboarding/opt-in-to-tanssi/opt-in-to-tanssi-6.webp
  images/node-operators/validators/onboarding/register-in-symbiotic/register-in-symbiotic-1.webp
  images/node-operators/validators/onboarding/register-in-symbiotic/register-in-symbiotic-2.webp
  images/node-operators/validators/onboarding/register-in-symbiotic/register-in-symbiotic-3.webp
  llms.txt
  node-operators/validators/onboarding/.pages
  node-operators/validators/onboarding/index.md
  node-operators/validators/onboarding/opt-in-to-tanssi.md
  node-operators/validators/onboarding/register-in-symbiotic.md
  variables.yml
Labels: A0 - New Content, B1 - Ready to Merge, C2 - High

#243 Adds validators subsection to the node operators section
  .snippets/text/node-operators/validators/onboarding/run-a-validator/intro.md
  .snippets/text/node-operators/validators/onboarding/run-a-validator/prerequisites.md
  images/node-operators/validators/onboarding/opt-in-to-tanssi/opt-in-to-tanssi-1.webp
  images/node-operators/validators/onboarding/opt-in-to-tanssi/opt-in-to-tanssi-2.webp
  images/node-operators/validators/onboarding/opt-in-to-tanssi/opt-in-to-tanssi-3.webp
  images/node-operators/validators/onboarding/opt-in-to-tanssi/opt-in-to-tanssi-4.webp
  images/node-operators/validators/onboarding/opt-in-to-tanssi/opt-in-to-tanssi-5.webp
  images/node-operators/validators/onboarding/opt-in-to-tanssi/opt-in-to-tanssi-6.webp
  images/node-operators/validators/onboarding/register-in-symbiotic/register-in-symbiotic-1.webp
  images/node-operators/validators/onboarding/register-in-symbiotic/register-in-symbiotic-2.webp
  images/node-operators/validators/onboarding/register-in-symbiotic/register-in-symbiotic-3.webp
  llms.txt
  node-operators/validators/onboarding/.pages
  node-operators/validators/onboarding/index.md
  node-operators/validators/onboarding/opt-in-to-tanssi.md
  node-operators/validators/onboarding/register-in-symbiotic.md
  variables.yml
Labels: A0 - New Content, B1 - Ready to Merge
