Repository moondance-labs/tanssi-docs, pull requests merged in 2025-07, with the labels that each got.

#289 Fix Timeline URL
  .snippets/text/node-operators/operators/onboarding/onboarding-timeline.json
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#296 Add URL to PR link checker workflow
  .github/workflows/pr-link-checker.yml
  builders/toolkit/integrations/oracles/acurast.md
  builders/toolkit/integrations/oracles/phala.md
  llms-full.txt
Labels: A2 - Maintenance Minor

#300 Applies feedback for collator guides
  .snippets/code/node-operators/sequencers/onboarding/run-a-sequencer/sequencers-docker/docker-command.md
  llms-full.txt
  node-operators/sequencers/onboarding/account-setup.md
  node-operators/sequencers/onboarding/run-a-sequencer/sequencers-systemd.md
Labels: A3 - Quick Fixes, C2 - High

#306 Running operators/nodes debug
  .snippets/code/node-operators/operators/onboarding/run-an-operator/operators-systemd/systemd-command.md
  builders/toolkit/ethereum-api/libraries/viem.md
  llms-files/llms-appchain.txt
  llms-files/llms-basics.txt
  llms-files/llms-custom-runtime.txt
  llms-files/llms-evm-template.txt
  llms-files/llms-operators.txt
  llms-files/llms-rpc-data-preservers.txt
  llms-files/llms-sequencers.txt
  llms-files/llms-substrate-template.txt
  llms-full.txt
  node-operators/network-node/tanssi/tanssi-node-docker.md
  node-operators/operators/onboarding/run-an-operator/operators-docker.md
Labels: A3 - Quick Fixes, C1 - Medium

#304 Dependency upgrade
  .CONTRIBUTING.md
  .nav.yml
  ai-resources/.nav.yml
  builders/.nav.yml
  builders/account-management/.nav.yml
  builders/build/.nav.yml
  builders/build/customize/.nav.yml
  builders/build/templates/.nav.yml
  builders/deploy/.nav.yml
  builders/interoperability/.nav.yml
  builders/manage/.nav.yml
  builders/manage/dapp/.nav.yml
  builders/manage/developer-portal/.nav.yml
  builders/tanssi-network/.nav.yml
  builders/tanssi-network/testnet/.nav.yml
  builders/toolkit/.nav.yml
  builders/toolkit/ethereum-api/.nav.yml
  builders/toolkit/ethereum-api/dev-env/.nav.yml
  builders/toolkit/ethereum-api/libraries/.nav.yml
  builders/toolkit/ethereum-api/precompiles/.nav.yml
  builders/toolkit/ethereum-api/wallets/.nav.yml
  builders/toolkit/integrations/.nav.yml
  builders/toolkit/integrations/indexers/.nav.yml
  builders/toolkit/integrations/indexers/sqd/.nav.yml
  builders/toolkit/integrations/oracles/.nav.yml
  builders/toolkit/integrations/wallet-integrations/.nav.yml
  builders/toolkit/substrate-api/.nav.yml
  builders/toolkit/substrate-api/dev-env/.nav.yml
  builders/toolkit/substrate-api/libraries/.nav.yml
  builders/toolkit/substrate-api/wallets/.nav.yml
  learn/.nav.yml
  learn/decentralized-networks/.nav.yml
  learn/framework/.nav.yml
  learn/tanssi/.nav.yml
  learn/tanssi/external-security-providers/.nav.yml
  learn/tanssi/network-features/.nav.yml
  learn/tanssi/network-services/.nav.yml
  node-operators/.nav.yml
  node-operators/network-node/.nav.yml
  node-operators/network-node/tanssi-powered-network/.nav.yml
  node-operators/network-node/tanssi/.nav.yml
  node-operators/operators/.nav.yml
  node-operators/operators/offboarding/.nav.yml
  node-operators/operators/onboarding/.nav.yml
  node-operators/operators/onboarding/run-an-operator/.nav.yml
  node-operators/operators/operational-tasks/.nav.yml
  node-operators/operators/operational-tasks/upgrade-your-node/.nav.yml
  node-operators/sequencers/.nav.yml
  node-operators/sequencers/offboarding/.nav.yml
  node-operators/sequencers/onboarding/.nav.yml
  node-operators/sequencers/onboarding/run-a-sequencer/.nav.yml
  node-operators/sequencers/operational-tasks/.nav.yml
  node-operators/sequencers/operational-tasks/upgrade-your-node/.nav.yml
Labels: A2 - Maintenance Minor, B1 - Ready to Merge
