Repository moondance-labs/tanssi-docs, pull requests merged in 2025-08, with the labels that each got.

#303 patches llms snippet regex, updates llms files
  scripts/generate_llms_standard.py
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#313 RPC & Archive nodes revisit
  .snippets/code/node-operators/network-node/rpc-docker/docker-command-mainnet.md
  .snippets/code/node-operators/network-node/rpc-docker/docker-command-testnet.md
  .snippets/code/node-operators/network-node/rpc-docker/terminal/pulling-docker-image.md
  .snippets/code/node-operators/network-node/rpc-systemd/parameters-mainnet.md
  .snippets/code/node-operators/network-node/rpc-systemd/parameters-testnet.md
  .snippets/text/node-operators/appchains-docker-data-directory.md
  .snippets/text/node-operators/appchains-systemd-data-directory.md
  .snippets/text/node-operators/network-node/bootnode-item.md
  .snippets/text/node-operators/network-node/getting-specs-files.md
  .snippets/text/node-operators/network-node/intro.md
  llms-files/llms-rpc-data-preservers.txt
  llms-files/llms-sequencers.txt
  llms-full.txt
  llms.txt
  node-operators/network-node/tanssi-powered-network/rpc-docker.md
  node-operators/network-node/tanssi-powered-network/rpc-systemd.md
  node-operators/sequencers/onboarding/run-a-sequencer/sequencers-docker.md
  node-operators/sequencers/onboarding/run-a-sequencer/sequencers-systemd.md
Labels: A1 - Maintenance Major, C1 - Medium

#323 Rewrites intros for operators
  .snippets/text/node-operators/operators/onboarding/run-an-operator/intro.md
  llms-files/llms-operators.txt
  llms-full.txt
  llms.txt
  node-operators/operators/onboarding/account-setup.md
  node-operators/operators/onboarding/index.md
  node-operators/operators/onboarding/opt-in-to-tanssi.md
  node-operators/operators/onboarding/register-in-symbiotic.md
  node-operators/operators/onboarding/run-an-operator/operators-docker.md
  node-operators/operators/onboarding/run-an-operator/operators-systemd.md
Labels: A2 - Maintenance Minor, B1 - Ready to Merge, C1 - Medium
